get http://localhost:3003/api/users/6122f81c511a4848a0938652
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXI1IiwiaWQiOiI2MTIyZjgzYjUxMWE0ODQ4YTA5Mzg2NjIiLCJpYXQiOjE2Mjk3MzIxMzIsImV4cCI6MTYyOTczNTczMn0.wzmzyWp0qUiM7fXjlOpTtxaJu3qBzwTedGsTAA0x_V4